# Generated by Django 2.2.7 on 2019-12-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(max_length=11)),
                ('updated_by', models.IntegerField(max_length=11)),
                ('deleted_by', models.IntegerField(max_length=11)),
                ('deleted', models.IntegerField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11)),
                ('detail', models.TextField()),
                ('type_product', models.CharField(max_length=11)),
                ('packing', models.CharField(max_length=11)),
                ('crt', models.IntegerField(max_length=11)),
                ('pcs', models.IntegerField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(max_length=11)),
                ('updated_by', models.IntegerField(max_length=11)),
                ('deleted_by', models.IntegerField(max_length=11)),
                ('deleted', models.IntegerField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=11)),
                ('role_type', models.IntegerField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(max_length=11)),
                ('updated_by', models.IntegerField(max_length=11)),
                ('deleted_by', models.IntegerField(max_length=11)),
                ('deleted', models.IntegerField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=11)),
                ('customers_name', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('status', models.IntegerField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(max_length=11)),
                ('updated_by', models.IntegerField(max_length=11)),
                ('deleted_by', models.IntegerField(max_length=11)),
                ('deleted', models.IntegerField(default=0, max_length=1)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fd.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt', models.IntegerField(max_length=11)),
                ('pcs', models.IntegerField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(max_length=11)),
                ('updated_by', models.IntegerField(max_length=11)),
                ('deleted_by', models.IntegerField(max_length=11)),
                ('deleted', models.IntegerField(default=0, max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fd.Products')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fd.Transaction')),
            ],
        ),
    ]
