# Generated by Django 2.2.7 on 2019-12-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0002_auto_20191203_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detail_transaction',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
