# Generated by Django 2.2.7 on 2019-12-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0006_auto_20191203_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='packing',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_product',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
